FROM rust:latest

RUN apt-get update && \
    apt-get install -y bubblewrap && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /usr/src/app

RUN cargo install cargo-watch

COPY Cargo.toml Cargo.lock ./

COPY . .

VOLUME ["/usr/src/app/server"]

EXPOSE 8080

CMD ["cargo", "watch", "--ignore", "server/*", "-x", "run --features full-stack"]