services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/workspaces/gameserver-rs:cached
      - /var/run/docker.sock:/var/run/docker.sock
    # We use a standard bridge so 'app' stays up even if k3d is busy
    networks:
      - dev-net
    command: /bin/sh -c "while sleep 1000; do :; done"

  k3d:
    image: ghcr.io/k3d-io/k3d:5.8.3-dind
    privileged: true
    networks:
      - dev-net
    volumes:
      - k3d-data:/var/lib/docker

networks:
  dev-net:
volumes:
  k3d-data:
