syntax = "proto3";

import "google/protobuf/struct.proto";

package main;

message MetadataTypes {
  string kind = 1;
  string data = 2;
}
message ApiCalls {
  string kind = 1;
  string data = 2;
}
message SrcAndDest {
  ApiCalls src = 1;
  ApiCalls dest = 2;
  string metadata = 3;
}
message MessagePayload {
  string type = 1;
  string message = 2;
  string authcode = 3;
}

message DeleteServerRequest {
  MetadataTypes metadata = 1;
}

message CreateServerRequest {
  MetadataTypes metadata = 1;
}

message StartServerRequest {}

message StopServerRequest {}

message ServerMessage {
  string authcode = 1;
  string data = 2;
  string type = 3;
}

message SetServerRequest {
  string message = 1;
  string type = 2;
  MetadataTypes metadata = 3;
  string authcode = 4;
}

message MigrateRequest {
  ApiCalls src = 1;
  ApiCalls dest = 2;
  string metadata = 3;
}
message ServerDataRequest {}

message ServerStateRequest {}

message ServerNameRequest {
  string type = 1;
  string message = 2;
  string authcode = 3;
}

message RawBytes {
  bytes byte_collection = 1;
}
message Ping {}
message IntegrationKeyRequest {
  google.protobuf.Struct key = 1;
}

message State {
  string name = 1;
  string start_keyword = 2;
  string stop_keyword = 3;
}
message ServerDataResponse {
  State state = 1;
}
message PingResponse {
  string message = 1;
}
message FileOperationResponse {
  string data = 1;
}
message CreateServerResponse {}
message DeleteServerResponse {}
message ServerStateResponse {
  MessagePayload message = 1; 
}
message ServerNameResponse {
  string type = 1;
  string message = 2;
  string authcode = 3;
}
message SetServerResponse {}
message StartServerResponse {}
message StopServerResponse {}

service ServerEdit {
  rpc Create(CreateServerRequest) returns (stream ServerMessage);
  rpc Delete(DeleteServerRequest) returns (DeleteServerResponse);
  rpc Start(stream ServerMessage) returns (stream ServerMessage);
  rpc Stop(StopServerRequest) returns (StopServerResponse);
}
service ServerManage {
  rpc Data(ServerDataRequest) returns (ServerDataResponse);
  rpc Name(ServerNameRequest) returns (ServerNameResponse);
  rpc State(ServerStateRequest) returns (ServerStateResponse);
  rpc Set(SetServerRequest) returns (SetServerResponse);
}
service General {

}
service Filesystem {

}